[package]
name = "people-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "People Rococo emulated chain (polkadot v1.15.0)"
publish = false

[dependencies]
sp-core.workspace = true
frame-support.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
people-rococo-runtime.workspace = true
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }

[features]
std = [
	"cumulus-primitives-core/std",
	"emulated-integration-tests-common/std",
	"frame-support/std",
	"sp-core/std"
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"people-rococo-runtime/runtime-benchmarks",
	"testnet-parachains-constants/runtime-benchmarks",
	"sp-core/runtime-benchmarks"
]
try-runtime = [
	"cumulus-primitives-core/try-runtime",
	"emulated-integration-tests-common/try-runtime",
	"frame-support/try-runtime",
	"parachains-common/try-runtime",
	"people-rococo-runtime/try-runtime",
	"testnet-parachains-constants/try-runtime",
	"sp-core/try-runtime"
]
