[package]
name = "rococo-runtime-constants"
version = "16.0.0"
description = "Constants used throughout the Rococo network. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
smallvec = { workspace = true, default-features = true }
frame-support.workspace = true
polkadot-primitives.workspace = true
polkadot-runtime-common.workspace = true
sp-runtime.workspace = true
sp-weights.workspace = true
sp-core.workspace = true
xcm.workspace = true
xcm-builder.workspace = true

[features]
default = ["std"]
std = [
	"frame-support/std",
	"polkadot-primitives/std",
	"polkadot-runtime-common/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
	"xcm-builder/std",
	"xcm/std",
]

# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"sp-core/runtime-benchmarks",
	"xcm/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"polkadot-primitives/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"sp-runtime/try-runtime",
	"xcm-builder/try-runtime",
	"sp-core/try-runtime",
	"xcm/try-runtime"
]
